max_jobs: 1

environment:
  CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: "true"

image: Visual Studio 2022

cache:
  - '%LocalAppData%\NuGet\v3-cache'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

install:
  - cmd: dotnet tool restore

build_script:
  - cmd: dotnet cake --target=Full

test: false

artifacts:
  - path: outputs\*.nupkg
    name: packages
  - path: outputs\*.snupkg
    name: symbols
  - path: outputs\tests\report
    name: report
    type: zip

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch:
        - master
        - main
      appveyor_repo_tag: true
  - provider: Environment
    name: GitHub
    on:
      branch:
        - master
        - main
      appveyor_repo_tag: true
  - provider: GitHub
    on:
      branch:
        - master
        - main
      appveyor_repo_tag: true
    auth_token:
      secure: Qv4tMB9BvNni2+v69vK38jQq2ga1+GiI/YqCWkiA1fZN72v2NtaZo6UpwmXQNkop
    artifact: /.*.nupkg/
