using System.Collections.Generic;
using System.Text;

namespace InsightArchitectures.Utilities.JsonSchema.Internal
{
    /// <summary>
    /// Generates C# source code (nullable-enabled records) from a <see cref="SchemaNode"/> tree.
    /// </summary>
    internal static class CodeEmitter
    {
        /// <summary>
        /// Emits a complete C# source file for the given schema.
        /// </summary>
        /// <param name="ns">The namespace to place the generated types in.</param>
        /// <param name="rootTypeName">The name of the root record type.</param>
        /// <param name="schema">The root schema node.</param>
        /// <returns>A string containing the generated C# source.</returns>
        public static string Emit(string ns, string rootTypeName, SchemaNode schema)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            // Collect all types (root + nested) in traversal order.
            var allTypes = new List<(string Name, SchemaNode Schema)>();
            CollectTypes(schema, rootTypeName, allTypes);

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
                foreach (var entry in allTypes)
                {
                    EmitRecord(sb, entry.Schema, entry.Name, allTypes, indent: 1);
                    sb.AppendLine();
                }

                sb.AppendLine("}");
            }
            else
            {
                foreach (var entry in allTypes)
                {
                    EmitRecord(sb, entry.Schema, entry.Name, allTypes, indent: 0);
                    sb.AppendLine();
                }
            }

            return sb.ToString();
        }

        private static string Indent(int level) => new string(' ', level * 4);

        /// <summary>
        /// Recursively collects all types (root + nested object properties) in DFS order.
        /// Each nested object type is named <c>parentName + PascalCase(propertyName)</c>.
        /// </summary>
        private static void CollectTypes(
            SchemaNode schema,
            string typeName,
            List<(string Name, SchemaNode Schema)> result)
        {
            result.Add((typeName, schema));

            foreach (var kvp in schema.Properties)
            {
                var csharpName = ToPascalCase(kvp.Key);
                var propSchema = kvp.Value;

                if (IsObjectWithProperties(propSchema))
                {
                    CollectTypes(propSchema, typeName + csharpName, result);
                }
                else if (string.Equals(propSchema.Type, "array", System.StringComparison.OrdinalIgnoreCase)
                    && propSchema.Items != null
                    && IsObjectWithProperties(propSchema.Items))
                {
                    CollectTypes(propSchema.Items, typeName + csharpName + "Item", result);
                }
            }
        }

        private static bool IsObjectWithProperties(SchemaNode s) =>
            string.Equals(s.Type, "object", System.StringComparison.OrdinalIgnoreCase)
            && s.Properties.Count > 0
            && s.AdditionalProperties is null;

        /// <summary>Emits a single <c>record</c> declaration for the given schema node.</summary>
        private static void EmitRecord(
            StringBuilder sb,
            SchemaNode schema,
            string typeName,
            List<(string Name, SchemaNode Schema)> allTypes,
            int indent)
        {
            var ind = Indent(indent);
            var ind2 = Indent(indent + 1);

            if (!string.IsNullOrWhiteSpace(schema.Description))
            {
                sb.AppendLine($"{ind}/// <summary>{EscapeXml(schema.Description!)}</summary>");
            }

            sb.Append($"{ind}public record {typeName}(");

            var parameters = new List<string>();

            foreach (var kvp in schema.Properties)
            {
                var propName = kvp.Key;
                var propSchema = kvp.Value;
                var csharpName = ToPascalCase(propName);
                var isRequired = schema.Required.Contains(propName) && !propSchema.IsNullableType;
                var csharpType = ResolveCSharpType(propSchema, typeName, csharpName, isRequired, allTypes);

                parameters.Add($"\n{ind2}{csharpType} {csharpName}");
            }

            if (parameters.Count > 0)
            {
                sb.Append(string.Join(",", parameters));
                sb.AppendLine();
                sb.AppendLine($"{ind});");
            }
            else
            {
                sb.AppendLine(");");
            }
        }

        private static string ResolveCSharpType(
            SchemaNode schema,
            string parentTypeName,
            string propertyName,
            bool isRequired,
            List<(string Name, SchemaNode Schema)> allTypes)
        {
            var baseType = ResolveBaseType(schema, parentTypeName, propertyName, allTypes);
            var nullable = !isRequired || schema.IsNullableType;
            return nullable ? MakeNullable(baseType) : baseType;
        }

        private static string ResolveBaseType(
            SchemaNode schema,
            string parentTypeName,
            string propertyName,
            List<(string Name, SchemaNode Schema)> allTypes)
        {
            if (string.Equals(schema.Type, "object", System.StringComparison.OrdinalIgnoreCase))
            {
                if (schema.AdditionalProperties != null)
                {
                    var valueType = ResolveBaseType(schema.AdditionalProperties, parentTypeName, propertyName, allTypes);
                    return $"global::System.Collections.Generic.Dictionary<string, {valueType}>";
                }

                if (schema.Properties.Count > 0)
                {
                    return parentTypeName + propertyName;
                }
            }

            if (string.Equals(schema.Type, "array", System.StringComparison.OrdinalIgnoreCase))
            {
                if (schema.Items != null)
                {
                    var itemType = ResolveBaseType(schema.Items, parentTypeName, propertyName + "Item", allTypes);
                    return itemType + "[]";
                }

                return "object[]";
            }

            return MapPrimitive(schema.Type, schema.Format);
        }

        /// <summary>Maps a JSON Schema primitive type + optional format hint to a C# type name.</summary>
        private static string MapPrimitive(string? type, string? format)
        {
            if (string.Equals(type, "string", System.StringComparison.OrdinalIgnoreCase))
            {
                if (string.Equals(format, "date-time", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "global::System.DateTimeOffset";
                }

                if (string.Equals(format, "date", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "global::System.DateOnly";
                }

                if (string.Equals(format, "time", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "global::System.TimeOnly";
                }

                if (string.Equals(format, "uri", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "global::System.Uri";
                }

                if (string.Equals(format, "uuid", System.StringComparison.OrdinalIgnoreCase)
                    || string.Equals(format, "guid", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "global::System.Guid";
                }

                if (string.Equals(format, "byte", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "byte[]";
                }

                return "string";
            }

            if (string.Equals(type, "integer", System.StringComparison.OrdinalIgnoreCase))
            {
                if (string.Equals(format, "int64", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "long";
                }

                return "int";
            }

            if (string.Equals(type, "number", System.StringComparison.OrdinalIgnoreCase))
            {
                if (string.Equals(format, "float", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "float";
                }

                return "double";
            }

            if (string.Equals(type, "boolean", System.StringComparison.OrdinalIgnoreCase))
            {
                return "bool";
            }

            return "object";
        }

        private static string MakeNullable(string type)
        {
            if (type.EndsWith("?", System.StringComparison.Ordinal))
            {
                return type;
            }

            return type + "?";
        }

        /// <summary>Converts a camelCase, snake_case, or kebab-case name to PascalCase.</summary>
        internal static string ToPascalCase(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return name;
            }

            var sb = new StringBuilder(name.Length);
            var capitalizeNext = true;

            foreach (var c in name)
            {
                if (c == '_' || c == '-' || c == ' ')
                {
                    capitalizeNext = true;
                }
                else if (capitalizeNext)
                {
                    sb.Append(char.ToUpperInvariant(c));
                    capitalizeNext = false;
                }
                else
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }

        private static string EscapeXml(string text) =>
            text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
