version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Restore "Cake.Tool" .NET Core local tool
          command: |
            dotnet tool restore
      - run:
          name: Build
          command: |
            dotnet cake --verbosity=Verbose
