version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Install .NET 5.0
          command: |
            &powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1')))"
      - run:
          name: Restore "Cake.Tool" .NET Core local tool
          command: |
            dotnet tool restore
      - run:
          name: Build
          command: |
            dotnet cake --verbosity=Verbose
